a = input('Digite Algo. ')

print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços.', a.isspace())
print('É um numero. ', a.isnumeric())
print('É alfabetico. ', a.isalpha())
print('É alfanumerico. ', a.isalnum())
print('É Maiusculo.', a.isupper())
print('É minusculo.', a.islower())
print('É capitalizado.', a.istitle())