nome = input('Digite Um nome. ')
nM = nome.upper()
nm = nome.lower()
ndivi = nome.split()
nr = ''.join(ndivi)
ntotal = len(nr)
npri = len(ndivi[0])

print('='*12)
print(nome)
print(nM)
print(nm)
print(nr)
print(ndivi)
print(ntotal)
print(npri)
print('='*12)
